# Generated by Django 2.1.1 on 2018-09-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargocult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='route',
            field=models.TextField(verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='license',
            name='track',
            field=models.CharField(max_length=10, verbose_name='Номерной знак'),
        ),
    ]
